EXPLAIN ANALYZE SELECT * FROM COINCIDENCIAS WHERE ESTADO = 'Aceptado';
EXPLAIN ANALYZE SELECT * FROM COINCIDENCIAS_PARTICIONADA WHERE ESTADO = 'Aceptado';

EXPLAIN ANALYZE SELECT * FROM COINCIDENCIAS WHERE ESTADO = 'Rechazado';
EXPLAIN ANALYZE SELECT * FROM COINCIDENCIAS_PARTICIONADA WHERE ESTADO = 'Rechazado';

EXPLAIN ANALYZE SELECT * FROM COINCIDENCIAS WHERE ESTADO = 'En espera';
EXPLAIN ANALYZE SELECT * FROM COINCIDENCIAS_PARTICIONADA WHERE ESTADO = 'En espera';

EXPLAIN ANALYZE SELECT * FROM BLOQUEO WHERE FECHA >= ('2022-01-01') AND FECHA <= ('2022-12-31');
EXPLAIN ANALYZE SELECT * FROM BLOQUEO_PARTICIONADA WHERE FECHA >= ('2022-01-01') AND FECHA <= ('2022-12-31');

EXPLAIN ANALYZE SELECT * FROM BLOQUEO WHERE FECHA >= ('2023-01-01') AND FECHA <= ('2023-06-30');
EXPLAIN ANALYZE SELECT * FROM BLOQUEO_PARTICIONADA WHERE FECHA >= ('2023-01-01') AND FECHA <= ('2023-06-30');

EXPLAIN ANALYZE SELECT * FROM MENSAJE WHERE FECHA >= ('2022-01-01') AND FECHA <= ('2022-12-31');
EXPLAIN ANALYZE SELECT * FROM MENSAJES_PARTICIONADA WHERE FECHA >= ('2022-01-01') AND FECHA <= ('2022-12-31');

 
